// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModularWolverine.Modules.Devices.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModularWolverine.Modules.Devices.Infrastructure.Database.Migrations
{
    [DbContext(typeof(DevicesDbContext))]
    [Migration("20260922143722_InitialDevices")]
    partial class InitialDevices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("devices")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModularWolverine.Modules.Devices.Domain.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("uuid")
                        .HasColumnName("imei");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Imei")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imei");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("Imei")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_imei");

                    b.ToTable("devices", "devices", t =>
                        {
                            t.Property("Imei")
                                .HasColumnName("imei1");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
