<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../ModularWolverine.Modules.Devices.Application/ModularWolverine.Modules.Devices.Application.csproj" />
        <ProjectReference Include="../ModularWolverine.Modules.Devices.Domain/ModularWolverine.Modules.Devices.Domain.csproj" />
    </ItemGroup>

</Project>

